### ISSUE TITLE
Suggestion to update

### ISSUE THREAD

**Issue by darylknight** [delaneymethod/mix#3]
Hi!

Firstly, thank you - I've been using this on all our Craft projects for years.

Everything is working perfectly, just thought I'd suggest that it might be worth updating this plugin even with something tiny - just to show it still works and is active?
People tend to stay away from things that haven't been updated for years, and Pixel & Tonic have said a few times they're considering filtering out plugins that haven't been updated.

**Comment by seandelaney** [comment]
Updated Craft requirement version to 3.6.7 as per Dependabot recommendations.

**Comment by darylknight** [comment]
Excellent, thanks!
